"""
FastAPI application for the Cloud SRE Triage Environment.

Three tasks of increasing difficulty:
  - sre-triage-easy   (EASY)   — single service down, restart it
  - sre-triage-medium (MEDIUM) — DB connection pool exhaustion
  - sre-triage-hard   (HARD)   — cascading failure, multi-step resolution

Endpoints (auto-generated by openenv):
  GET  /health       — liveness probe
  GET  /metadata     — environment name + description
  GET  /schema       — action / observation / state JSON schemas
  POST /reset        — reset the environment
  POST /step         — execute one action
  GET  /state        — current environment state
  POST /mcp          — JSON-RPC 2.0 MCP endpoint
  GET  /openapi.json — OpenAPI spec (used by openenv validate)

Usage:
  uvicorn server.app:app --host 0.0.0.0 --port 7860
  uv run server
  python -m server.app
"""

import os
import uvicorn

from openenv.core.env_server.http_server import create_app

try:
    from ..models import SREAction, SREObservation
    from .sre_easy_environment import SREEasyEnvironment
    from .sre_medium_environment import SREMediumEnvironment
    from .sre_hard_environment import SREHardEnvironment
except ImportError:
    from models import SREAction, SREObservation
    from server.sre_easy_environment import SREEasyEnvironment
    from server.sre_medium_environment import SREMediumEnvironment
    from server.sre_hard_environment import SREHardEnvironment

# ---------------------------------------------------------------------------
# Select which task to serve based on TASK env var (default: easy)
# The hackathon validator will call each task separately by setting this var.
# ---------------------------------------------------------------------------
TASK = os.getenv("SRE_TASK", "easy").lower().strip()

_ENV_MAP = {
    "easy":   SREEasyEnvironment,
    "medium": SREMediumEnvironment,
    "hard":   SREHardEnvironment,
    # Allow full task names too
    "sre-triage-easy":   SREEasyEnvironment,
    "sre-triage-medium": SREMediumEnvironment,
    "sre-triage-hard":   SREHardEnvironment,
}

EnvClass = _ENV_MAP.get(TASK, SREEasyEnvironment)

# Build the app — openenv auto-wires /reset, /step, /state, /health,
# /metadata, /schema, /mcp, and /openapi.json
app = create_app(
    EnvClass,
    SREAction,
    SREObservation,
    env_name="sre-triage",
    max_concurrent_envs=1,
)


def main(host: str = "0.0.0.0", port: int | None = None) -> None:
    """
    Entry point for uv run server / pyproject.toml [project.scripts].

    Called by:
        uv run server
        python -m server.app
    """
    _port = port or int(os.getenv("PORT", 7860))
    uvicorn.run(app, host=host, port=_port, log_level="info")


if __name__ == "__main__":
    main()
